# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shiva Sharan Palakurthi
user_description: I'm a Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles. 
user_title: Software Engineer
email: shivasharanpalakurthi490@gmail.com
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: p shiva sharan
github_username:  shiva490
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

